### ISSUE TITLE
why it is not supported to set the local port in a TCP client connection 

### ISSUE THREAD

**Issue by zhjdhx** [fatedier/golib#26]
![image](https://github.com/fatedier/golib/assets/18984061/d68eaa3f-10e2-4fb5-b1e4-a9b401a9ec69)

When I use the TCP protocol of frp for port forwarding installation requirements, I would like to specify the local client port because some ports on the local machine need to be reserved for other services to be installed.

**Comment by fatedier** [comment]
Currently there are no plans, this is not a common requirement, you may consider using other tools in combination.
